"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from typing import Optional
from urllib.parse import parse_qs, unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _default_db_host_from_supabase_api_url() -> Optional[str]:
    """https://<ref>.supabase.co -> db.<ref>.supabase.co (must match the project for SUPABASE_DB_PASSWORD)."""
    raw = (os.environ.get("VITE_SUPABASE_URL") or os.environ.get("SUPABASE_URL") or "").strip()
    if not raw:
        return None
    host = urlparse(raw).hostname or ""
    if host.endswith(".supabase.co") and host.count(".") >= 2:
        ref = host.split(".")[0]
        return f"db.{ref}.supabase.co"
    return None


def _django_pg_from_url(url: str) -> dict:
    """Parse postgresql://... for Django (use Supabase Session pooler URI if direct db.* fails DNS)."""
    normalized = url.strip().replace("postgresql+psycopg2://", "postgresql://")
    u = urlparse(normalized)
    if u.scheme not in ("postgres", "postgresql"):
        raise ValueError(f"SUPABASE_DATABASE_URL must be postgres/postgresql, got: {u.scheme}")
    dbname = (u.path or "").lstrip("/") or "postgres"
    if not u.hostname:
        raise ValueError("SUPABASE_DATABASE_URL missing host")
    q = parse_qs(u.query)
    sslmode = (q.get("sslmode") or ["require"])[0]
    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": dbname,
        "USER": unquote(u.username) if u.username else "postgres",
        "PASSWORD": unquote(u.password) if u.password else "",
        "HOST": u.hostname,
        "PORT": str(u.port or 5432),
        "OPTIONS": {"sslmode": sslmode},
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5_t5y)o(_8qfa94m%ipiovx3r6e9-ed@-4e-8ie4f5ze4%l4cp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Postgres on Supabase — see manage.py load_dotenv for Smart-CSM/.env
#
# If `python manage.py migrate` fails with "could not translate host name":
#   - `db.<ref>.supabase.co` is often IPv6-only; Windows/psycopg2 often cannot use it.
#   - Fix: Supabase → Settings → Database → copy **Session pooler** URI (IPv4-friendly).
#     Put it in Smart-CSM/.env as SUPABASE_DATABASE_URL=postgresql://...
#     Use **Session** mode for DDL/migrations (Transaction pooler can break Django migrate).
#
# Priority: SUPABASE_DATABASE_URL (or DATABASE_URL) > SUPABASE_DB_PASSWORD + host fields > SQLite
_pg_url = (os.environ.get("SUPABASE_DATABASE_URL") or os.environ.get("DATABASE_URL") or "").strip()
if _pg_url:
    DATABASES = {"default": _django_pg_from_url(_pg_url)}
elif os.environ.get("SUPABASE_DB_PASSWORD"):
    _host = os.environ.get("SUPABASE_DB_HOST") or _default_db_host_from_supabase_api_url()
    if not _host:
        raise ValueError(
            "SUPABASE_DB_PASSWORD is set but the DB host is unknown. Set SUPABASE_DB_HOST, "
            "or VITE_SUPABASE_URL (https://<ref>.supabase.co), or use SUPABASE_DATABASE_URL."
        )
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("SUPABASE_DB_NAME", "postgres"),
            "USER": os.environ.get("SUPABASE_DB_USER", "postgres"),
            "PASSWORD": os.environ["SUPABASE_DB_PASSWORD"],
            "HOST": _host,
            "PORT": os.environ.get("SUPABASE_DB_PORT", "5432"),
            "OPTIONS": {"sslmode": os.environ.get("SUPABASE_DB_SSLMODE", "require")},
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
